version: '2.1'

services:

  app:
    build:
      context: .
      dockerfile: src/test-integration/resources/Dockerfile
    ports:
      - "9876:9876"
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./src/test-integration/resources/prometheus:/etc/prometheus
      - prom_data:/src/test-integration/resources/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./src/test-integration/resources/grafana:/etc/grafana/provisioning/datasources

  db:
    image: postgres
    restart: always
    ports:
      - "9877:5432"
    environment:
      POSTGRES_DB: "vmcentral"
      POSTGRES_USER: "vmcentral"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d vmcentral -U vmcentral" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  prom_data: